
# build system configuration for the project
[build-system]
requires = ["setuptools>=64.0.0", "wheel"]
build-backend = "setuptools.build_meta"

# project-specific metadata
[project]
name = "py-maze"
version = "1.0.0"